[package]
name = "phoebe"
version = "0.0.0"
edition = "2021"
description = "Automatic differentiation for Rust."
license = "MIT"
repository = "https://github.com/samestep/phoebe"
include = ["src/lib.rs"]
